### ISSUE TITLE
GitHub releases are stale

### ISSUE THREAD

**Issue by ewanmellor** [steinbergmedia/bravura#10]
On https://github.com/steinbergmedia/bravura/releases, the latest release shown is 1.18.

This is two years older than the latest release in https://github.com/steinbergmedia/bravura/tree/master/releases (bravura-1.211.zip).

Please tag the latest release on GitHub; I was about to file a bug that's already been fixed :-)

**Comment by rettinghaus** [comment]
Yes, please make "proper" releases. On https://www.smufl.org/ it is said that 
> Bravura is currently at version 1.276, which implements SMuFL 1.2.

But even the releases folder stops at `bravura-1.211`.

**Comment by dspreadbury** [comment]
I've removed the old *Releases* folder from the repo, and created GitHub releases for the last couple of years' worth of font releases.
