### ISSUE TITLE
Metadata file glyph codepoints are slightly out of sync with font

### ISSUE THREAD

**Issue by tisimst** [steinbergmedia/bravura#11]
As of Bravura v1.271:

With the addition of condensed, sans serif time signature glyphs in the range U+F4EE - U+F505 and the condensed "normal" time signature glyphs in the range U+F506 - U+F52A, the glyph codepoints for all glyphs after that no longer match what's found in the metadata file.

For example, the glyph "fClef5Below" shows up at codepoint at U+F52B, but the metadata says it's at U+F4EE, which is where it used to be. The last glyph affected by this is "timeSig12over8" which is now found at U+F5F3, but the metadata file says is should be at U+F5B6 (where it used to be).

**Comment by dspreadbury** [comment]
This is still not right as of today's 1.35 release, but I'll figure this out before the next release.

**Comment by dspreadbury** [comment]
I spent a few minutes more looking into this and I've been able to sort it out in 831aeaf.

**Comment by tisimst** [comment]
Thank you! This definitely helps keep things sorted properly.
