### ISSUE TITLE
Huge advance width in musicalsymbolornamentstroke4

### ISSUE THREAD

**Issue by ClintGoss** [steinbergmedia/bravura#18]
I am seeing an advance width for musicalsymbolornamentstroke4 (U+1D19E), glyph 3258 in Bravura Text v1.277 of 65536 ... maybe intended to be -1?

**Comment by dspreadbury** [comment]
Sorry not to have looked at this issue for so long. I've checked this glyph and I believe the negative width to be "correct" (for some value of correct!). The idea is that this glyph can be added to one of the existing ornament glyphs by typing it afterwards. It would be more elegant to use a set of ligatures that produces the correct appearance when this glyph is added directly after one of the ornaments with which it is intended to combine.

I honestly can't remember why I did it this way, but I expect it was following the example of Adobe Sonata Std, the OpenType version of Sonata, to my knowledge the only font besides Bravura that has ever implemented the Unicode Musical Symbols range.

**Comment by ClintGoss** [comment]
Thanks for looking into this!

BTW, I think there are a number of fonts that implement 220 or more of the 231 characters in the Musical Symbols block (as of Unicode v12.1). I have logged: Symbola and Musica (George Duros), a flock of ElbSound fonts (which I think are copies of other open source fonts), Nishi-Teki (231 characters implemented), and Noto Music (231).
