### ISSUE TITLE
Time signatures behave abnormally in WOFF2 format

### ISSUE THREAD

**Issue by JGgithub2018** [steinbergmedia/bravura#20]
I'm using JSDelivr to get the files from this repository.

In this [repl.it project](https://Metronome-v2.jackyguo1.repl.co), the glyphs in the "Time Signature" section's combo boxes are supposed to be raised to the numerator position. But:

1. Multiple characters overlap (the 1 and 2 in 12 are overlapped, similar for 16)
2. The characters do not move, even though there is a _timeSigCombNumerator_

**Comment by JGgithub2018** [comment]
A workaround for the first part is to add a four-per-em space in between each character

**Comment by dspreadbury** [comment]
I believe this is a duplicate of #25. I'll close this issue and report any further findings there.
