### ISSUE TITLE
wiggleGlissando registration

### ISSUE THREAD

**Issue by erikronstrom** [steinbergmedia/bravura#21]
![image](https://user-images.githubusercontent.com/8256399/74934768-33cf5d00-53e7-11ea-969b-c26378dc7ab6.png)

As of Bravura 1.32, there are two problems with wiggleGlissando:

1) It does not stand on the baseline but almost one staff space above it

2) The right side bearing is off, so tessellation is not correct when drawing a string of multiple glissando marks

(On a side note, to me it is annoying that the wiggle glyphs stand on the baseline rather than being centered around it, but that could of course be a matter of taste, programming-wise)

**Comment by dspreadbury** [comment]
Apologies for this problem. I've just now fixed it (though the fix isn't included in today's 1.35 release). I'll make sure this makes it into the next release.

<img width="559" alt="improved-tesselation" src="https://user-images.githubusercontent.com/1312874/77770084-9e099c00-703c-11ea-8eba-9e9941b9dcc7.png">

**Comment by dspreadbury** [comment]
This is fixed in [bravura-1.360](https://github.com/steinbergmedia/bravura/releases/tag/bravura-1.360).
