### ISSUE TITLE
Please add git tags to repository

### ISSUE THREAD

**Issue by alerque** [steinbergmedia/bravura#22]
The last git tag seems to be 1.271. On the website it says 1.276 is the latest. I just noticed the actual OTF font files claim to be 1.320 now!

Can we please git some new git tags for the releases up to the present so that distro packages can update without having to manually sort through commits?

**Comment by dspreadbury** [comment]
Sorry for the lack of interim tags. I've added a new tag for today's 1.35 release and will be sure to create tags for each new release from now on.
