### ISSUE TITLE
Retire SVG versions of Bravura and Bravura Text

### ISSUE THREAD

**Issue by dspreadbury** [steinbergmedia/bravura#23]
There is almost no browser support for SVG fonts any longer, per [this page](https://caniuse.com/#feat=svg-fonts) and [this discussion](https://www.zachleat.com/web/retire-bulletproof-syntax/), so I plan to stop producing an SVG version of Bravura and Bravura Text with immediate effect.

**Comment by tisimst** [comment]
Yay! I've wondered about this for a long time.

**Comment by dspreadbury** [comment]
As of Bravura 1.37, SVG versions of both Bravura and Bravura Text will once again be part of the distribution. These SVG versions are being produced by processing the OTF versions of Bravura and Bravura Text using [https://cloudconvert.com/otf-ot-svg](https://cloudconvert.com/otf-ot-svg).
