### ISSUE TITLE
New tag has non semantic version

### ISSUE THREAD

**Issue by alerque** [steinbergmedia/bravura#24]
Thanks for the 1.35 tag, but we have a new problem! This version number is smaller than 1.271 (the last official tag) and also smaller than 1.320 (the last unofficial release I fudged an Arch Linux package for by patching in a tag).

I know in the font likely says 1.350 internally since three digit numbers are traditional (SIL & OpenFV recommendations) but the git tag needs to reflect that as well so that package managers understand that 1.350 is newer than 1.271.

**Comment by dspreadbury** [comment]
The bravura-1.35 tag has been replaced with a bravura-1.350 tag.

**Comment by alerque** [comment]
Thanks!
