### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by cmloegcmluin** [steinbergmedia/bravura#25]
I am planning to build a web application that will use the Bravura Text font to display the results of musical calculations as staff notation (using the [combining staff position characters](https://www.w3.org/2019/03/smufl13/tables/combining-staff-positions.html)). Initial experiments are inconclusive regarding wide browser support of Bravura Text. Some of them are displaying Bravura Text as if it were just the Bravura font. 

Should I expect any browser that supports OTF to do the right thing with the combining staff position characters? 

Is it only the OTF version of the font that implements the combining staff position characters, or should the WOFF versions do it too?

**Comment by cmloegcmluin** [comment]
After investigating further, we've discovered that in the WOFF and WOFF2 versions of Bravura Text, the glyphs exist for the ligatures of position and accidental, but the lookup tables that provide the connection from the pairs of code points to the single glyphs seem to be missing.

I attempted to patch the problem myself in FontForge, manually adding back one ligature lookup to see if that would solve the problem. Unfortunately my experiment was inconclusive, because the updated font I generate from FontForge shows as bounding boxes (and this happens even if I make no changes to the font before generating). This failure is not an issue with Bravura, of course -- it is with either FontForge, the format, or most likely myself. Nonetheless, I am stuck, but I thought it'd be prudent to update you here with this information.

I'm on Windows 10, with the Bravura fonts temporarily uninstalled locally, testing in both Chrome and Firefox. Only the WOFF2 format directly from the release here is working in my web app; the other formats display as bounding boxes, just like the WOFF2 I've exported from FontForge.

**Comment by dspreadbury** [comment]
Sorry not to have responded to this sooner. Bravura is just one of my many responsibilities so I don't always have time to jump on these issues when they arise.

I will need to investigate why the WOFF and WOFF2 versions of Bravura Text are missing all of the look-up tables. I guess this is a tooling problem. I'm using [FontPlop](https://github.com/matthewgonzalez/fontplop/releases) to convert the OTF generated from FontLab into EOT and WOFF/WOFF2, and something must be going awry in that process. I've not yet had a chance to look into this but I'll try to in the next few weeks.

In the meantime, if you're going to the trouble of trying to build a web application to display music notation, might you be better off using "real" Bravura and drawing the staff lines etc. using primitives, then performing the positioning of the musical symbols directly? I don't know what kind of application you're trying to build, but it might even be that using an existing library for displaying notation in the browser, such as [Vexflow](https://github.com/0xfe/vexflow) or [Verovio](https://github.com/rism-ch/verovio) might be an acceptable approach for your project?

**Comment by cmloegcmluin** [comment]
Thank you Daniel. I understand you have quite a lot on your plate. There is no particular rush on this.

I had not yet considered Vexflow or Verovio, but I will investigate them ASAP. Thanks for the recommendations!

**Comment by dspreadbury** [comment]
As part of the latest Bravura 1.37 update, I've generated the woff/woff2/eot files directly using FontLab rather than using the FontPlop tool I've previously been using. I believe this should be preserving the feature tables. Please let me know if you don't find this to be the case.
