### ISSUE TITLE
 Some character's permission as private use

### ISSUE THREAD

**Issue by cortix** [steinbergmedia/bravura#26]
When I try to install, Norton constantly detects InstallBravura-1.204.exe as a virus.
Somehow, I installed it. But I see some character's permission as private use. 
This is the screenshot of it.
https://www.screencast.com/t/DHM2SAtEI

**Comment by dspreadbury** [comment]
"Private Use" refers to the Unicode range in which all of SMuFL's characters are located. SMuFL uses the Private Use Area in the Basic Multi-lingual Plane, which can read about e.g. [here](https://en.wikipedia.org/wiki/Private_Use_Areas).
