### ISSUE TITLE
Trill symbol is ugly

### ISSUE THREAD

**Issue by dbenjaminmiller** [steinbergmedia/bravura#28]
![old](https://user-images.githubusercontent.com/43855846/85523084-835fa880-b5d4-11ea-8913-95817746377a.png)
Look at that. Notice that weird little imperfection?
![new](https://user-images.githubusercontent.com/43855846/85523109-8bb7e380-b5d4-11ea-9ac6-473a04c7dc29.png)
Now, that's much better.

I've attached a ZIP of the fixed version (as an EPS). I claim absolutely no copyright on it, since I really have not done any original contribution, but I can say whatever you'd like, just as long as you fix the symbol! 
[uniE566_Bravura.zip](https://github.com/steinbergmedia/bravura/files/4824134/uniE566_Bravura.zip)

**Comment by dbenjaminmiller** [comment]
![image](https://user-images.githubusercontent.com/43855846/85525050-b30fb000-b5d6-11ea-9578-d1105f8cefbe.png)
The same problem (little tiny issues) applies to a number of other characters too, e.g., this one. But the trill sticks out the most since it is alphabetic.

**Comment by dspreadbury** [comment]
Fixed in f97d82a
