### ISSUE TITLE
Missing information in SVG

### ISSUE THREAD

**Issue by rettinghaus** [steinbergmedia/bravura#3]
In the latest version of Bravura.svg the `<metadata>`, `@font-family`, and all the `@glyph-name` disappeared. Is this intentional, and if yes, why? 
Could it be brought back?

**Comment by dspreadbury** [comment]
Unfortunately the software we were using for producing the SVG font is no longer maintained, and we're now using a tool that is effectively only a wrapper around FontForge's SVG export feature.
