### ISSUE TITLE
BravuraText.woff2: @font-face load error (chrome, firefox)

### ISSUE THREAD

**Issue by h-sug1no** [steinbergmedia/bravura#32]
Hi!

I'm trying to load the BravuraText.woff2 by using css `@font-face` rule, but I'm getting the cmap error in chrome and firefox. Is this a known limitation?

---

test case:
https://jsfiddle.net/xda128b7/3/

w10/chrome( 83.0.4103.116（Official Build）): 
```
Failed to decode downloaded font: https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/woff/BravuraText.woff2
?editor_console=:1
OTS parsing error: cmap: Failed to parse table
```
<img src="https://user-images.githubusercontent.com/59550999/86566678-fe499b80-bfa4-11ea-8d97-3600304aed82.png" height="300">

w10/firefox(78.0.1):

```
downloadable font: cmap: Final segment start and end must be 0xFFFF (0xF52B-0xFFFF) (font-family: "BravuraText" style:normal weight:400 stretch:100 src index:0) source: https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/woff/BravuraText.woff2

downloadable font: cmap: Failed to parse format 4 cmap subtable 0 (font-family: "BravuraText" style:normal weight:400 stretch:100 src index:0) source: https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/woff/BravuraText.woff2

downloadable font: cmap: Failed to parse table (font-family: "BravuraText" style:normal weight:400 stretch:100 src index:0) source: https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/woff/BravuraText.woff2

downloadable font: rejected by sanitizer (font-family: "BravuraText" style:normal weight:400 stretch:100 src index:0) source: https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/woff/BravuraText.woff2
```

osx/safari 13.1.1(13609.2.9.1.3);
BravuraText.woff2 is loaded with no error.

Best Regard,

**Comment by h-sug1no** [comment]
1) Testing with the .otf fonts:
    https://jsfiddle.net/gr8jfq09/2/
    The result is same as woff2 fonts test. (Only BravuraText.otf failed to load).

2) I validated Bravura.otf and BravuraText.otf by using <https://github.com/HinTak/Font-Validator/>, then 
`W0020	Tables are not in optimal order	table 'cmap' precedes table 'name'` was reported for BravuraText.otf only. 

3) I made BravuraText2.otf from BravuraText.otf by using ttx(<https://github.com/adobe-type-tools/afdko>)  roundtrip for an attempt to fix the order of tables:

    ```shell
    $ ttx -o t.ttx BravuraText.otf
    $ ttx -o BravuraText2.otf t.ttx
    ```
    Then, about BravuraText2.otf:

    - `W0020`was not reported by Font-Validator
    - loaded via `@font-face` (chrome/firefox) without errors
      
        ![image](https://user-images.githubusercontent.com/59550999/87002763-465efd00-c1f5-11ea-800c-1df0b55839ed.png)

4) This means that the most likely cause of this problem is the order of the 'cmap' and 'name' tables. (I don't know why the tables are in the wrong order...) Or maybe it's a limitation of chorome/firefox...

The attached file ([issue32-1.zip](https://github.com/steinbergmedia/bravura/files/4894827/issue32-1.zip)) contains the following directories:

- ttx-test: t.ttx, BravuraText2.otf created by using ttx and html for testing.
- FontValidatorReports: Report files generated by FontValidator

I hope this helps.

**Comment by h-sug1no** [comment]
https://jsfiddle.net/pukots8L/19/
<img src="https://user-images.githubusercontent.com/59550999/98049612-5faa4a00-1e73-11eb-8d64-ffc638466956.png" width="300">

Thank you for fixing this issue!
Version 72b1ec424baff2bbd2265b20b39e0e9a08b55c86 of {otf, woff, woff2} can load without error with {w10:chrome, w10:firefox, osx:safari}.

**Comment by Originfx** [comment]
Still see this bug in version 1.393

**Comment by h-sug1no** [comment]
current master = 3df1714e6f9d522a8d2b6ee6888fa3e68e71199d (Daniel Spreadbury Bumped Bravura Text to version 1.393; this fixes the incorrect style ...): Still see this problem (BravuraText.otf only)
https://jsfiddle.net/Lxkpcw51/

![image](https://user-images.githubusercontent.com/59550999/112402528-0a9ea000-8d50-11eb-851c-dc19c71992c1.png)
