### ISSUE TITLE
Bravura fixed width font for editing?

### ISSUE THREAD

**Issue by Glenn-smufl** [steinbergmedia/bravura#4]
0049 0074 0020 0069 0073 0020 0068 0061 0072 0064 0020 0074 006F 0020 0072 0065 0061 0064 0020 0068 0065 0078 0020 0063 006F 0064 0065 0020 0070 006F 0069 006E 0074 0073 002E

Some might be able to read the above, because it is ASCII, and ASCII has been around for a while. But while editing or viewing HTML/SVG files containing Bravura font codes, it either looks like the above, or like the following:

![ss_20170216_213252](https://cloud.githubusercontent.com/assets/16694420/23053632/e6387f18-f48f-11e6-80a1-d79501efc65f.png)

While both are decipherable, neither is friendly and readable.

BravuraText?  Well, it has its place, but isn't intended for displaying characters separately, but rather in groups, so a sequence of Bravura characters is likely to produce some unintended display consequences.

Bravura itself? Well, even more so than Bravura Text, it is variable width (which a fair number of text editors can't handle), and when the text is embedded in other code and text, doesn't have all the other Unicode glyphs.

Suggest a BravuraMono for text editing purposes... for editing source files containing Bravura symbols, as long as the editor can do font substitutions so that multiple monospaced fonts can be examined for finding the characters.  One could put BravuraMono first, and fall back to the collection of regular fonts, or put BravuraMono last.  BravuraMono wouldn't need glyphs in the standard ASCII/Latin regions which are well covered by other fonts, but if it had some, then the order of searching would select from different fonts.

Yeah, it would be a lot of work for a limited purpose, but it sure would make examining the source or HTML or SVG files containing Bravura a lot easier.  If a particular symbol can't be recognized because of its size and complexity, one can either zoom in, or ask the editor for the character code, or copy/paste to a different application. But most common characters are likely to be somewhat recognizable even at normal text sizes.  The point here is to avoid the combining done by BravuraText and the odd sizes of some characters in Bravura, by reducing them to a monospaced representation of individual characters.

**Comment by dspreadbury** [comment]
This isn't something I can see us working on in the near future. If somebody wants to tackle the production of a FontLab script that can produce a fixed-width version of Bravura in a sensible fashion, then I'd be open to considering this further.
