### ISSUE TITLE
Unable to install on 2015 MacBook Air

### ISSUE THREAD

**Issue by rhertzman** [steinbergmedia/bravura#40]
When I try to install the Bravura Font using Packages on an early 2015 MacBook Air running OS Catalina (10.15.7), I get the following message: 'The document “Bravura Font Family.pkgproj” could not be opened. The data is not in the correct format.'

**Comment by dspreadbury** [comment]
That's not an installer. That's a script to **build** an installer. If you want to install the font, grab the raw OTF files from [here](https://github.com/steinbergmedia/bravura/tree/master/redist/otf).
