### ISSUE TITLE
Providing TTF variant by default in Dorico to boost its content-drawing speed and UI responsiveness.

### ISSUE THREAD

**Issue by ShikiSuen** [steinbergmedia/bravura#45]
https://forums.steinberg.net/t/use-opentype-truetype-variant-of-bravura-to-boost-dorico-ui-responsiveness/696433

**Comment by ShikiSuen** [comment]
(Intel CPU are inefficient in drawing massive cubic-curved contents. Using OpenType TrueType music fonts can thereotically boost rendering speed comparing to using OpenType PostScript fonts.)

**Comment by dspreadbury** [comment]
I don't believe this would have any impact on the responsiveness of the user interface of Dorico or indeed of any application using Bravura. Unless there is a broader need in the community for a version of the font with TrueType outlines I don't plan to create and maintain one.
