### ISSUE TITLE
Chromatic Solfege 

### ISSUE THREAD

**Issue by ledvinam** [steinbergmedia/bravura#5]
Hello, 

we are unable to have correctly rendered chromatic solfege on a staff if we use accidentals in given key. Also for Minor keys the current solfege noteheads are not complete. I can not for example "visually" sing Minor3rd. 

 “do, di, re, ri, mi, fa, fi, so(l), si, la, li, ti, (do)” and “do, ti, te, la, le so(l), se, fa, mi, me, re, ra (do)"

Thank you, Marek.

**Comment by dspreadbury** [comment]
This will be taken care of when w3c/smufl#82 is taken care of, which we expect to do in the SMuFL 1.4 milestone.
