### ISSUE TITLE
ornamentMordentInverted is missing from bravura_metadata.json

### ISSUE THREAD

**Issue by techlover10** [steinbergmedia/bravura#51]
In use, it seems to have the same bounding box as the ornamentMordent, but it's missing from the metadata file.

**Comment by Jojo-Schmitz** [comment]
IIRC it has been removed, and changed roles with ornamentShortTrill and ornamentMordent, already a while ago.

**Comment by techlover10** [comment]
Ah, yep, a Google search with this in mind revealed how I confused myself - it still shows up here: https://www.smufl.org/version/latest/range/commonOrnaments/ as being available.  A closer inspection of this page reveals that it is for v1.2 of the spec, despite the URL showing up in Google searches with "latest" in it.  I suppose the bug is that it would be nice if this page indicated more prominently that it is out of date. :)

**Comment by Jojo-Schmitz** [comment]
Instead check https://w3c.github.io/smufl/latest/tables/common-ornaments.html

**Comment by techlover10** [comment]
Thanks for the tip!  I've seen that page too, but mistakenly assumed that both were equivalently "latest" and just published in different places (and thus, I didn't recognize the differences).  User error!
