### ISSUE TITLE
Bravura .iss Installer Does Not Work In Windows - LicenseFile Path Incorrect

### ISSUE THREAD

**Issue by AlteriusOmega** [steinbergmedia/bravura#60]
The Windows installer will not run in Inno because there is a bug on line 27 which is the path to LicenseFile. The full line is below:
LicenseFile=Z:\git\bravura\redist\OFL.txt

Obviously this path isn't going to exist on Windows computers.

The error message is below:
Error: The system cannot find the path specified

Also, users should not have to download Inno or any other 3rd party program just to install these fonts. They should either be TTF, OTF or use a .exe installer.

Thanks,
Sam

**Comment by dspreadbury** [comment]
Thanks for your feedback, Sam. The InnoSetup script is intended as a template to help other font developers who need to know how to install a font, rather than as a means of actually distributing Bravura. But perhaps the repository should make that fact clearer. I'll definitely think about it!
