### ISSUE TITLE
Missing tag for 1.393

### ISSUE THREAD

**Issue by LiberalArtist** [steinbergmedia/bravura#61]
The latest Git tag in this repository is `bravura-1.392`, which is [marked in GitHub](https://github.com/steinbergmedia/bravura/releases/tag/bravura-1.392) as a pre-release beta for SMuFL 1.4. Since then, SMuFL 1.4 has been released, and the [announcement](https://www.smufl.org/smufl-1-4-released/) says that "SMuFL 1.4 is implemented by version 1.392 of the Bravura reference font".

However, I see in the history that Bravura Text 1.392 used an incorrect style name, which was corrected to `Regular` in https://github.com/steinbergmedia/bravura/commit/3df1714e6f9d522a8d2b6ee6888fa3e68e71199d as a version 1.393.

It would be a great help as a distro packager of Bravura if we could have a `bravura-1.393` tag for commit 3df1714.

I also see that commit 3df1714 did *not* create a Bravura 1.393 (as opposed to Bravura Text). This is less of an issue for me personally, but, if it isn't too much trouble, it might be even better to add a new commit to be tagged `bravura-1.400` updating the versions of both fonts. This would:

1. clearly communicate that the fonts are out of beta; and
2. make it obvious that the Bravura and Bravura Text releases go together.

Thanks for the lovely font and for all of the work on SMuFL!

**Comment by dspreadbury** [comment]
Yes, you’re quite right that there hasn’t been an official Bravura release following the SMuFL 1.4 release. Sorry about that! There are a couple of mop-up tasks that also need to be done on the fonts, and I will try to prioritise them in the next week or two.
