### ISSUE TITLE
Is octave+ displacement of notes possible?

### ISSUE THREAD

**Issue by StephenBuley** [steinbergmedia/bravura#78]
Maybe I am just totally not understanding how to do this, but I am using Bravura Text and struggling to write anything beyond the ranges of Ab3 and C#6 (treble clef). I have found the unicode values for moving the note/ledger line placement up to 8 positions, but there are several notes on either side of this range that are common to see in both bass clef and treble clef, even for beginning students. Is there any support for this that I am not finding, or an easy work around?

Thanks!

**Comment by bitsybabe** [comment]
Ironically I just filed a similar issue. How are you compositing the ledger lines with the staff and note values?  I am finding that the ledger lines are completely random and are forcing me to write horrible code since each new line is a new algorithm.  I'm curious how you've solve this?

**Comment by StephenBuley** [comment]
@bitsybabe I haven't solved this, I'm not quite sure what you are asking - basically I write the staff, then write in the unicode value for moving the cursor up 6 spaces (or lines) which is U+EB95, then draw the ledger line, then put in the code for however many spaces I want the note to go up (lets say six again to go directly on the ledger line), then draw the quarter note or whatever. After each glyph, the "cursor" goes back to the middle of the staff, the third line, and you have to go from there. Maybe that is what you are saying? I just want to know how to draw ledger lines and notes further than 8 spaces away from the middle of the staff.

**Comment by kenmcd** [comment]
What version of the font are you using?
I think v1.393 is the "fixed" version.

**Comment by bitsybabe** [comment]
I put the code I'm using in my issue (which appears just before yours). I didn't know that I would be expected to mix glyphs and graphics so I was attempting to use the ledger line glyphs to extend the staff, but since the lines are astonishingly random, I'm going to have to keep track of a lot more static multipliers to do so.

My plan for when I get past the first octave is to use the `8va-----` modifier and go back down into the staff, then the `15va------` after that.  I don't think anyone can very easily read more than a few ledger lines.

**Comment by StephenBuley** [comment]
I am not sure which version of the font I am using @kenmcd, is there an easy way to find that out?
@bitsybabe I guess that is an ok work around, but there are people who read more than two ledger lines daily, the app I am trying to create teaches middle schoolers, they aren't used to seeing 8va or 8vb octave displacements, or even changing clefs. Something like [this fingering chart](https://norlanbewley.com/bewleymusic/trombone-slide-position-chart/) is what I am trying to replicate, ledger lines and all.

**Comment by StephenBuley** [comment]
[Here is the website](https://band-fingerings.vercel.app) I am using this in if this helps for context

**Comment by StephenBuley** [comment]
Closed, I ended up solving my problem using pngs of generated notes instead of generating them with bravura text. Thanks.
